--移动端登录tokenId记录
DROP TABLE A_TOKENRECORDS;
CREATE TABLE A_TOKENRECORDS
(
  ID         NUMBER(19) NOT NULL,
  USERCODE   VARCHAR2(50) NOT NULL,
  TOKEN    VARCHAR2(100) NOT NULL,
  CREATEDATE TIMESTAMP(9)
);
COMMENT ON TABLE A_TOKENRECORDS IS '手机端登录token记录';
COMMENT ON COLUMN A_TOKENRECORDS.ID IS '标识';
COMMENT ON COLUMN A_TOKENRECORDS.USERCODE IS '用户code';
COMMENT ON COLUMN A_TOKENRECORDS.TOKEN IS '用户Token';
COMMENT ON COLUMN A_TOKENRECORDS.CREATEDATE IS '操作时间';
--移动端登录tokenId记录
CREATE INDEX IDX_TOKENRECORDS_USERCODE on A_TOKENRECORDS(USERCODE);